services:
  local-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - api-network
    depends_on:
      - couchdb
  
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  couchdb_data: